version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ProductionAppDb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  migrate:
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ProductionAppDb;Username=user;Password=pass"

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.Server
    depends_on:
      - db
    ports:
      - "5000:8080"
    networks:
      - app-network
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ProductionAppDb;Username=user;Password=pass"
      ASPNETCORE_ENVIRONMENT: Development

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.Client
    depends_on:
      - server
    ports:
      - "5001:80"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
