FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ProductionApp.Client/ProductionApp.Client.csproj ProductionApp.Client/
RUN dotnet restore ProductionApp.Client/ProductionApp.Client.csproj
COPY . .
WORKDIR /src/ProductionApp.Client
RUN dotnet publish -c Release -o /app/publish

FROM nginx:alpine AS runtime
COPY --from=build /app/publish/wwwroot /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
